<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationHighDpiMode>SystemAware</ApplicationHighDpiMode>
    <RollForward>Major</RollForward>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>LegionChromaFlow</AssemblyName>
    <RootNamespace>LegionChromaFlow</RootNamespace>
    <InvariantGlobalization>true</InvariantGlobalization>
    <UseAppHost>false</UseAppHost>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <NoWarn>CA1416</NoWarn>
  </PropertyGroup>

</Project>
